### ISSUE TITLE
Pip takes too long to resolve dependencies

### ISSUE THREAD

**Issue by DavidePaglieri** [google-research/frame-interpolation#10]
Hello!

While doing `pip install -r frame_interpolation/requirements.txt` I get the following message multiple times

`INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking`

I have waited for hours, however, the process is very slow. Could you please release stricter constraints in the requirements.txt so that the dependency resolver has an easier time installing it? 

In alternative, do you have a conda .yml configuration file to share? 

Thank you!

**Comment by DavidePaglieri** [comment]
I solved it by manually installing mediapy, scikit-image and apache-beam with conda forge.
Now however I get this error when running on GPU

`python3 -m eval.interpolator_cli --pattern "photos" --model_path pretrained_models/film_net/Style/saved_model --times_to_interpolate 3 --output_video
2022-02-17 16:46:42.425391: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:42.432424: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:42.433143: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
W0217 16:46:42.508855 139912741675840 environments.py:371] Make sure that locally built Python SDK docker image has Python 3.8 interpreter.
I0217 16:46:42.509001 139912741675840 environments.py:380] Default Python SDK image for environment is apache/beam_python3.8_sdk:2.31.0
I0217 16:46:42.539682 139912741675840 translations.py:636] ==================== <function annotate_downstream_side_inputs at 0x7f3f923d4e50> ====================
I0217 16:46:42.541225 139912741675840 translations.py:636] ==================== <function fix_side_input_pcoll_coders at 0x7f3f923d4f70> ====================
I0217 16:46:42.541358 139912741675840 translations.py:636] ==================== <function pack_combiners at 0x7f3f923d5430> ====================
I0217 16:46:42.541591 139912741675840 translations.py:636] ==================== <function lift_combiners at 0x7f3f923d54c0> ====================
I0217 16:46:42.541673 139912741675840 translations.py:636] ==================== <function expand_sdf at 0x7f3f923d5670> ====================
I0217 16:46:42.541758 139912741675840 translations.py:636] ==================== <function expand_gbk at 0x7f3f923d5700> ====================
I0217 16:46:42.541872 139912741675840 translations.py:636] ==================== <function sink_flattens at 0x7f3f923d5820> ====================
I0217 16:46:42.541966 139912741675840 translations.py:636] ==================== <function greedily_fuse at 0x7f3f923d58b0> ====================
I0217 16:46:42.542194 139912741675840 translations.py:636] ==================== <function read_to_impulse at 0x7f3f923d5940> ====================
I0217 16:46:42.542325 139912741675840 translations.py:636] ==================== <function impulse_to_input at 0x7f3f923d59d0> ====================
I0217 16:46:42.542466 139912741675840 translations.py:636] ==================== <function sort_stages at 0x7f3f923d5c10> ====================
I0217 16:46:42.542651 139912741675840 translations.py:636] ==================== <function setup_timer_mapping at 0x7f3f923d5b80> ====================
I0217 16:46:42.542816 139912741675840 translations.py:636] ==================== <function populate_data_channel_coders at 0x7f3f923d5ca0> ====================
I0217 16:46:42.543538 139912741675840 statecache.py:172] Creating state cache with size 100
I0217 16:46:42.544226 139912741675840 worker_handlers.py:890] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x7f3f921b7f70> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0217 16:46:42.544367 139912741675840 fn_runner.py:519] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-2979-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)
2022-02-17 16:46:42.810725: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-17 16:46:42.811406: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:42.812270: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:42.812951: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:43.542891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:43.543655: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:43.544439: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-17 16:46:43.545060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13795 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0217 16:46:47.290272 139912741675840 interpolator_cli.py:151] Generating in-between frames for photos.
2022-02-17 16:46:50.431386: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-02-17 16:46:50.432772: W ./tensorflow/stream_executor/stream.h:2090] attempting to perform DNN operation using StreamExecutor without DNN support
2022-02-17 16:46:50.435487: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-02-17 16:46:50.436709: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
2022-02-17 16:46:50.438901: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-02-17 16:46:50.440120: W ./tensorflow/stream_executor/stream.h:2090] attempting to perform DNN operation using StreamExecutor without DNN support
2022-02-17 16:46:50.442462: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-02-17 16:46:50.443676: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1223, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/home/wizard/FILM/eval/interpolator_cli.py", line 152, in process
    frames = list(
  File "/home/wizard/FILM/eval/util.py", line 118, in interpolate_recursively_from_files
    yield from _recursive_generator(
  File "/home/wizard/FILM/eval/util.py", line 87, in _recursive_generator
    mid_frame = interpolator.interpolate(
  File "/home/wizard/FILM/eval/interpolator.py", line 104, in interpolate
    result = self._model(inputs, training=False)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 744, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'AvgPool' defined at (most recent call last):
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 178, in <module>
      app.run(main)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 303, in run
      _run_main(main, args)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
      sys.exit(main(argv))
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 174, in main
      _run_pipeline()
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 167, in _run_pipeline
      result = pipeline.run()
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/pipeline.py", line 564, in run
      return self.runner.run_pipeline(self, self._options)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
      return runner.run_pipeline(pipeline, options)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 191, in run_pipeline
      self._latest_run_result = self.run_via_runner_api(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 202, in run_via_runner_api
      return self.run_stages(stage_context, stages)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 366, in run_stages
      stage_results = self._run_stage(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 557, in _run_stage
      last_result, deferred_inputs, fired_timers = self._run_bundle(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 603, in _run_bundle
      result, splits = bundle_manager.process_bundle(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 905, in process_bundle
      result_future = self._worker_handler.control_conn.push(process_bundle_req)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
      response = self.worker.do_instruction(request)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 601, in do_instruction
      return getattr(self, request_type)(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 632, in process_bundle
      bundle_processor = self.bundle_processor_cache.get(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 458, in get
      processor = bundle_processor.BundleProcessor(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 864, in __init__
      op.setup()
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 138, in setup
      self.interpolator = interpolator_lib.Interpolator(
    File "/home/wizard/FILM/eval/interpolator.py", line 82, in __init__
      self._model = tf.compat.v2.saved_model.load(model_path)
Node: 'AvgPool'
dnn PoolForward launch failed
         [[{{node AvgPool}}]] [Op:__inference_restored_function_body_13284]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wizard/FILM/eval/interpolator_cli.py", line 178, in <module>
    app.run(main)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/wizard/FILM/eval/interpolator_cli.py", line 174, in main
    _run_pipeline()
  File "/home/wizard/FILM/eval/interpolator_cli.py", line 167, in _run_pipeline
    result = pipeline.run()
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/pipeline.py", line 564, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 191, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 202, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 366, in run_stages
    stage_results = self._run_stage(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 557, in _run_stage
    last_result, deferred_inputs, fired_timers = self._run_bundle(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 603, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 905, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
    response = self.worker.do_instruction(request)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 601, in do_instruction
    return getattr(self, request_type)(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 639, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 993, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 222, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 351, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 353, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1225, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1290, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1223, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1386, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1225, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1290, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1223, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1386, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1225, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1223, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/home/wizard/FILM/eval/interpolator_cli.py", line 152, in process
    frames = list(
  File "/home/wizard/FILM/eval/util.py", line 118, in interpolate_recursively_from_files
    yield from _recursive_generator(
  File "/home/wizard/FILM/eval/util.py", line 87, in _recursive_generator
    mid_frame = interpolator.interpolate(
  File "/home/wizard/FILM/eval/interpolator.py", line 104, in interpolate
    result = self._model(inputs, training=False)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 744, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
RuntimeError: tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'AvgPool' defined at (most recent call last):
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 178, in <module>
      app.run(main)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 303, in run
      _run_main(main, args)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
      sys.exit(main(argv))
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 174, in main
      _run_pipeline()
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 167, in _run_pipeline
      result = pipeline.run()
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/pipeline.py", line 564, in run
      return self.runner.run_pipeline(self, self._options)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
      return runner.run_pipeline(pipeline, options)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 191, in run_pipeline
      self._latest_run_result = self.run_via_runner_api(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 202, in run_via_runner_api
      return self.run_stages(stage_context, stages)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 366, in run_stages
      stage_results = self._run_stage(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 557, in _run_stage
      last_result, deferred_inputs, fired_timers = self._run_bundle(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 603, in _run_bundle
      result, splits = bundle_manager.process_bundle(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 905, in process_bundle
      result_future = self._worker_handler.control_conn.push(process_bundle_req)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
      response = self.worker.do_instruction(request)
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 601, in do_instruction
      return getattr(self, request_type)(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 632, in process_bundle
      bundle_processor = self.bundle_processor_cache.get(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 458, in get
      processor = bundle_processor.BundleProcessor(
    File "/home/wizard/miniconda/envs/FILM/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 864, in __init__
      op.setup()
    File "/home/wizard/FILM/eval/interpolator_cli.py", line 138, in setup
      self.interpolator = interpolator_lib.Interpolator(
    File "/home/wizard/FILM/eval/interpolator.py", line 82, in __init__
      self._model = tf.compat.v2.saved_model.load(model_path)
Node: 'AvgPool'
dnn PoolForward launch failed
         [[{{node AvgPool}}]] [Op:__inference_restored_function_body_13284] [while running 'Process directories']`

**Comment by fitsumreda** [comment]
Could it be an out of memory issue? Perhaps, you could try out on the photos in the repo.

**Comment by DavidePaglieri** [comment]
It wasn't an out of memory issue. I had the wrong CuDNN version installed on the VM and it was giving this error. Fixed now!
