### ISSUE TITLE
Interpolator error in Colab

### ISSUE THREAD

**Issue by qo4on** [google-research/frame-interpolation#39]
Hi!
I have an error when running [your Colab](https://colab.sandbox.google.com/drive/1sK0uc-GJxmdnaxHhYqD2afRknakpdTNZ). Everything seems to be set up correctly.
![image](https://user-images.githubusercontent.com/35609308/171752519-a22b716e-4344-4f59-af22-67420ce73381.png)

But the interpolator returns an error. What is wrong here?
```
!python3 -m frame_interpolation.eval.interpolator_cli \
     --pattern $folder \
     --fps $fps \
     --model_path $path \
     --times_to_interpolate $times \
     --output_video

W0602 23:02:59.550400 140164226131840 environments.py:374] Make sure that locally built Python SDK docker image has Python 3.7 interpreter.
I0602 23:02:59.550563 140164226131840 environments.py:380] Default Python SDK image for environment is apache/beam_python3.7_sdk:2.34.0
I0602 23:02:59.573410 140164226131840 translations.py:678] ==================== <function annotate_downstream_side_inputs at 0x7f79e1bc0e60> ====================
I0602 23:02:59.573622 140164226131840 translations.py:678] ==================== <function fix_side_input_pcoll_coders at 0x7f79e1bc0f80> ====================
I0602 23:02:59.573747 140164226131840 translations.py:678] ==================== <function pack_combiners at 0x7f79e1bc14d0> ====================
I0602 23:02:59.574009 140164226131840 translations.py:678] ==================== <function lift_combiners at 0x7f79e1bc1560> ====================
I0602 23:02:59.574106 140164226131840 translations.py:678] ==================== <function expand_sdf at 0x7f79e1bc1710> ====================
I0602 23:02:59.574208 140164226131840 translations.py:678] ==================== <function expand_gbk at 0x7f79e1bc17a0> ====================
I0602 23:02:59.574292 140164226131840 translations.py:678] ==================== <function sink_flattens at 0x7f79e1bc18c0> ====================
I0602 23:02:59.574381 140164226131840 translations.py:678] ==================== <function greedily_fuse at 0x7f79e1bc1950> ====================
I0602 23:02:59.574580 140164226131840 translations.py:678] ==================== <function read_to_impulse at 0x7f79e1bc19e0> ====================
I0602 23:02:59.574673 140164226131840 translations.py:678] ==================== <function impulse_to_input at 0x7f79e1bc1a70> ====================
I0602 23:02:59.574779 140164226131840 translations.py:678] ==================== <function sort_stages at 0x7f79e1bc1cb0> ====================
I0602 23:02:59.574893 140164226131840 translations.py:678] ==================== <function setup_timer_mapping at 0x7f79e1bc1c20> ====================
I0602 23:02:59.574995 140164226131840 translations.py:678] ==================== <function populate_data_channel_coders at 0x7f79e1bc1d40> ====================
I0602 23:02:59.575562 140164226131840 statecache.py:172] Creating state cache with size 100
I0602 23:02:59.576099 140164226131840 worker_handlers.py:894] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x7f79e1617310> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0602 23:02:59.576217 140164226131840 fn_runner.py:607] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-3222-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)
2022-06-02 23:03:02.950367: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0602 23:03:06.137572 140164226131840 interpolator_cli.py:155] Generating in-between frames for /content/input-frames.
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/content/frame_interpolation/eval/interpolator_cli.py", line 158, in process
    input_frames, _TIMES_TO_INTERPOLATE.value, self.interpolator))
  File "/content/frame_interpolation/eval/util.py", line 182, in interpolate_recursively_from_files
    yield util.read_image(frames[-1])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/frame_interpolation/eval/interpolator_cli.py", line 182, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/frame_interpolation/eval/interpolator_cli.py", line 178, in main
    _run_pipeline()
  File "/content/frame_interpolation/eval/interpolator_cli.py", line 171, in _run_pipeline
    result = pipeline.run()
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 573, in run
    return self.runner.run_pipeline(self, self._options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 196, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 206, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 385, in run_stages
    runner_execution_context, bundle_context_manager)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 653, in _run_stage
    bundle_manager))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 770, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1080, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
    response = self.worker.do_instruction(request)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 598, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 996, in process_bundle
    element.data)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 221, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 352, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 354, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1300, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1396, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1300, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1396, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1316, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/content/frame_interpolation/eval/interpolator_cli.py", line 158, in process
    input_frames, _TIMES_TO_INTERPOLATE.value, self.interpolator))
  File "/content/frame_interpolation/eval/util.py", line 182, in interpolate_recursively_from_files
    yield util.read_image(frames[-1])
IndexError: list index out of range [while running 'Process directories']
```

**Comment by fitsumreda** [comment]
This doesn't seem right.
I0602 23:03:06.137572 140164226131840 interpolator_cli.py:155] Generating in-between frames for /content/input-frames.
try folder='/content/input-frames/*' or '/content/input-frames/01'

**Comment by qo4on** [comment]
Thank you! I managed to run it. The asterisk did the job!
```
folder = '/content/input-frames/*' #@param {type:"string"}
times = 1 #@param {type:"slider", min:1, max:10, step:1}

if os.path.isdir('/content/gdrive/MyDrive/FILM/frame_interpolation/'):
    path = '/content/gdrive/MyDrive/FILM/frame_interpolation/pretrained_models/film_net/Style/saved_model'
else:
    path = '/content/frame_interpolation/pretrained_models/film_net/Style/saved_model'

!python3 -m frame_interpolation.eval.interpolator_cli \
    --pattern $folder \
    --model_path $path \
    --times_to_interpolate $times
```

But I'm not sure that everything works as it should. The result looks terrible. Is there any way to reduce the number of artifacts?
![image](https://user-images.githubusercontent.com/35609308/171767377-9c26fed2-9ab6-49b0-b17b-4c5fba99ee4b.png)

**Comment by fitsumreda** [comment]
You might want to train the frame interpolator on datasets that look like the ones you're testing, I'd hope you'll get better results. If you've other questions, feel free to re-open the issue.
