### ISSUE TITLE
google Colab: dnn PoolForward launch failed

### ISSUE THREAD

**Issue by kyrick** [google-research/frame-interpolation#56]
Hello! Months ago I created a colab for FILM which has worked successfully until today. I assume Colab changed something in their VM environment. Because all the FILM colabs are broken in the same way. Do you have any ideas which dependency might have changed?

Here's a link to my colab: https://colab.research.google.com/drive/1tbbbnQge0yb0LmnWNchEKNhjtBNC6jX-?authuser=1#scrollTo=JS_U-0Ot888M

**The error I'm seeing:**
```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
[<ipython-input-7-d90753e28670>](https://localhost:8080/#) in <module>
     80 for i in trange(len(frame_sets)):
     81     infiles = frame_sets[i]
---> 82     frames = list(util.interpolate_recursively_from_files(infiles, times_to_interpolate, interpolator))
     83 
     84     # pad the start of the animation if on the first frame

5 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InternalError: Graph execution error:
Detected at node 'AvgPool' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 381, in dispatch_queue
      yield self.process_one()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 346, in wrapper
      runner = Runner(result, future, yielded)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1080, in __init__
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 545, in execute_request
      user_expressions, allow_stdin,
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-7-d90753e28670>", line 77, in <module>
      interpolator = interpolator_lib.Interpolator(model_path)
    File "/content/frame_interpolation/eval/interpolator.py", line 82, in __init__
      self._model = tf.compat.v2.saved_model.load(model_path)
Node: 'AvgPool'
dnn PoolForward launch failed
	 [[{{node AvgPool}}]] [Op:__inference_restored_function_body_12706]
```

**Comment by krango** [comment]
Same issue here

**Comment by kyrick** [comment]
@krango I'm at a loss to what went wrong. I've tried two other FiLM colabs (the two linked on this github) and they both fail with the same error. Best I can figure is that google updated the VM environment and it broke the dependencies somehow.

**Comment by krango** [comment]
@kyrick I can't find a single working copy of FILM now.

**Comment by fitsumreda** [comment]
Thanks for catching this issue @kyrick . I will follow up with more information after consulting teams.

**Comment by kyrick** [comment]
Thank you @fitsumreda! I believe any colab implementation should demonstrate the problem. But if there's any details I can give you, or steps I can try please let me know.

**Comment by fitsumreda** [comment]
@kyrick @krango Here is a temporary solution. Update your `requirements_colab.txt` as below:
```
tensorflow==2.8.0 # The latest should include tensorflow-gpu
tensorflow-datasets==4.4.0
tensorflow-addons==0.15.0
apache-beam==2.34.0
mediapy==1.0.3
loguru
```

Apparently, tensorflow==2.6.2 is no longer working, but 2.8 seems to work fine for now. 

Will update the main, after figuring out the root cause.

**Comment by kyrick** [comment]
@fitsumreda beautiful! thank you so much! I was just coming to let you know we figured out the the tensorflow requirements issue but you beat me to it haha. I've updated my colab and it's working again ❤️

**Comment by fitsumreda** [comment]
Great 💯
