### ISSUE TITLE
PyTTI-Tools: FiLM.ipynb - doesn't start

### ISSUE THREAD

**Issue by xvoland** [google-research/frame-interpolation#63]
3. Interpolate!
Results will be saved in a subdirectory of frames_dir named "interpolated_frames"

2022-09-26 11:42:18.966 | INFO     | __main__:<module>:6 - Beginning interpolation...
2022-09-26 11:42:23.017 | DEBUG    | __main__:_run_pipeline:171 - ['frames']
W0926 11:42:23.081343 140189229807488 environments.py:374] Make sure that locally built Python SDK docker image has Python 3.7 interpreter.
I0926 11:42:23.081508 140189229807488 environments.py:380] Default Python SDK image for environment is apache/beam_python3.7_sdk:2.34.0
I0926 11:42:23.106427 140189229807488 translations.py:678] ==================== <function annotate_downstream_side_inputs at 0x7f7fc35227a0> ====================
I0926 11:42:23.106673 140189229807488 translations.py:678] ==================== <function fix_side_input_pcoll_coders at 0x7f7fc35228c0> ====================
I0926 11:42:23.106805 140189229807488 translations.py:678] ==================== <function pack_combiners at 0x7f7fc3522dd0> ====================
I0926 11:42:23.107073 140189229807488 translations.py:678] ==================== <function lift_combiners at 0x7f7fc3522e60> ====================
I0926 11:42:23.107178 140189229807488 translations.py:678] ==================== <function expand_sdf at 0x7f7fc3523050> ====================
I0926 11:42:23.107293 140189229807488 translations.py:678] ==================== <function expand_gbk at 0x7f7fc35230e0> ====================
I0926 11:42:23.107396 140189229807488 translations.py:678] ==================== <function sink_flattens at 0x7f7fc3523200> ====================
I0926 11:42:23.107529 140189229807488 translations.py:678] ==================== <function greedily_fuse at 0x7f7fc3523290> ====================
I0926 11:42:23.107744 140189229807488 translations.py:678] ==================== <function read_to_impulse at 0x7f7fc3523320> ====================
I0926 11:42:23.107830 140189229807488 translations.py:678] ==================== <function impulse_to_input at 0x7f7fc35233b0> ====================
I0926 11:42:23.107934 140189229807488 translations.py:678] ==================== <function sort_stages at 0x7f7fc35235f0> ====================
I0926 11:42:23.108054 140189229807488 translations.py:678] ==================== <function setup_timer_mapping at 0x7f7fc3523560> ====================
I0926 11:42:23.108170 140189229807488 translations.py:678] ==================== <function populate_data_channel_coders at 0x7f7fc3523680> ====================
I0926 11:42:23.108772 140189229807488 statecache.py:172] Creating state cache with size 100
I0926 11:42:23.109313 140189229807488 worker_handlers.py:894] Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x7f7fc2f0d390> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
I0926 11:42:23.109435 140189229807488 fn_runner.py:607] Running (((ref_AppliedPTransform_Create-directory-names-Impulse_3)+(ref_AppliedPTransform_Create-directory-names-FlatMap-lambda-at-core-py-3222-_4))+(ref_AppliedPTransform_Create-directory-names-Map-decode-_6))+(ref_AppliedPTransform_Process-directories_7)
2022-09-26 11:42:25.948001: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2022-09-26 11:42:29.362 | DEBUG    | __main__:process:158 - 0 frames detected.
I0926 11:42:29.363154 140189229807488 interpolator_cli.py:159] Generating in-between frames for frames.
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/interpolator_cli.py", line 162, in process
    input_frames, _TIMES_TO_INTERPOLATE.value, self.interpolator))
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/util.py", line 122, in interpolate_recursively_from_files
    yield util.read_image(frames[-1])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/interpolator_cli.py", line 187, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/interpolator_cli.py", line 183, in main
    _run_pipeline()
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/interpolator_cli.py", line 176, in _run_pipeline
    result = pipeline.run()
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 573, in run
    return self.runner.run_pipeline(self, self._options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 196, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 206, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 385, in run_stages
    runner_execution_context, bundle_context_manager)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 653, in _run_stage
    bundle_manager))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 770, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1080, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
    response = self.worker.do_instruction(request)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 598, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 996, in process_bundle
    element.data)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 221, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 352, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 354, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1300, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1396, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1300, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1396, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 216, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 714, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1316, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/interpolator_cli.py", line 162, in process
    input_frames, _TIMES_TO_INTERPOLATE.value, self.interpolator))
  File "/usr/local/lib/python3.7/dist-packages/frame_interpolation/eval/util.py", line 122, in interpolate_recursively_from_files
    yield util.read_image(frames[-1])
IndexError: list index out of range [while running 'Process directories']
2022-09-26 11:42:30.928 | INFO     | __main__:<module>:14 - Interpolation comlpete.

**Comment by xvoland** [comment]
GPU issue. Solve: Runtime -> Change Runtime type -> GPU

**Comment by fitsumreda** [comment]
Thanks updating with the fix.
